# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'StatsWalesRegistry'
  imageRepository: 'statswales-backend'
  containerRegistry: 'statswalesregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Marvell Consulting(3f7a282e-96dc-4706-9b9e-65609c29b2c8)'
        acrName: 'StatsWalesRegistry'
        acrUsername: 'StatsWalesRegistry'
        acrPassword: '$(acr_password)'
        dockerfilePath: 'Dockerfile'
        resourceGroup: 'statswales-container-app-rg'
        containerAppName: 'statswales-develop-backend'
        containerAppEnvironment: 'statswales-container-app-environment'
        targetPort: '3000'
        ingress: 'external'
        imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'
        environmentVariables: >
          APP_ENV=$(app_env)
          DB_HOST=$(db_host)
          DB_PORT=5432
          DB_USERNAME=$(db_username)
          DB_PASSWORD=$(db_password)
          DB_DATABASE=$(db_database)
          AZURE_DATALAKE_STORAGE_ACCOUNT_NAME=$(azure_datalake_storage_account_name)
          AZURE_DATALAKE_STORAGE_ACCOUNT_KEY=$(azure_datalake_storage_account_key)
          AZURE_DATALAKE_STORAGE_DIRECTORY_NAME=$(azure_datalake_storage_directory_name)
          AZURE_DATALAKE_STORAGE_FILESYSTEM_NAME=$(azure_datalake_storage_filesystem_name)
          AZURE_BLOB_STORAGE_ACCOUNT_NAME=$(azure_blob_storage_account_name)
          AZURE_BLOB_STORAGE_ACCOUNT_KEY=$(azure_blob_storage_account_key)
          AZURE_BLOB_STORAGE_CONTAINER_NAME=$(azure_blob_storage_container_name)
          BACKEND_URL=$(backend_url)
          FRONTEND_URL=$(frontend_url)
          SESSION_SECRET=$(session_secret)
          SESSION_STORE=$(session_store)
          JWT_SECRET=$(jwt_secret)
          JWT_EXPIRES_IN=$(jwt_expires_in)
          AUTH_PROVIDERS=$(auth_providers)
          GOOGLE_CLIENT_ID=$(google_client_id)
          GOOGLE_CLIENT_SECRET=$(google_client_secret)
          ONELOGIN_URL=$(onelogin_url)
          ONELOGIN_CLIENT_ID=$(onelogin_client_id)
          ONELOGIN_CLIENT_SECRET=$(onelogin_client_secret)
          ONELOGIN_PUBLIC_KEY=$(onelogin_public_key)
          ONELOGIN_PRIVATE_KEY=$(onelogin_private_key)
          REDIS_URL=$(redis_url)
          REDIS_ACCESS_KEY=$(redis_access_key)
