services:
  db-dev:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend

  db-test:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend-test

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"

  blobstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: 'azurite'
    # command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --debug=/tmp/debug.log
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
