services:
  db-dev:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend
    # volumes:
    #   - .docker/postgres/data:/var/lib/postgresql/data

  db-test:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend-test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # blob storage emulator
  blobstorage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite-blob --blobHost 127.0.0.1 --blobPort 10000"
    ports:
      - "10000:10000"
