services:
  db-dev:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend

  db-test:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend-test

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

  # blob storage emulator
  # blobstorage:
  #   image: mcr.microsoft.com/azure-storage/azurite
  #   command: "azurite-blob --blobHost 127.0.0.1 --blobPort 10000"
  #   ports:
  #     - "10000:10000"
