services:
  db-dev:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data

  db-test:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statswales-backend-test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
